import type { Metadata } from "next";
import { Providers } from "./providers";
import ConnectBar from '@/components/ConnectBar'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,modal
}: Readonly<{
  children: React.ReactNode;
  modal : React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>

        <Providers>
          <ConnectBar></ConnectBar>
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}



